@echo off
set arg1=%1
set arg2=%2

IF NOT EXIST "src\\main\\resources\\com\\example\\financingtool\\pre.txt" (
    echo Prerequisites not found
    echo ...
    :: Check for Python Installation
    python --version 2>NUL
    if errorlevel 1 goto errorNoPython

    :: Reaching here means Python is installed.
    :: Execute stuff...

    echo ...
    echo Upgrading pip...
    python -m pip install --upgrade pip
    echo ...
    echo Installing Selenium...
    pip install --upgrade selenium
    echo ...
    echo Installing PIL...
    pip install --upgrade pillow
    echo ...
    echo Installing colorama...
    pip install --upgrade colorama
    echo ...
    echo Prerequisites installed> src\\main\\resources\\com\\example\\financingtool\\pre.txt
)
echo Taking screenshot...
python src\\main\\resources\\com\\example\\financingtool\\%arg1% %arg2%

exit
:: Once done, exit the batch file -- skips executing the errorNoPython section
goto:eof

:errorNoPython
echo ...
echo Error^: Python not installed
echo ...
echo Installing Python...
winget install -e --id Python.Python.3.11 --no-upgrade --accept-package-agreements --accept-source-agreements
REM winget install python --no-upgrade --accept-package-agreements --accept-source-agreements
echo ...
echo Please reboot your PC
echo ...